name: Build and publish a Docker image to ghcr.io and Docker Hub
on:

  # publish on releases (tagged as "x.y.z" - "v" prefix is removed)
  release:
    types: [ published ]

  # publish on pushes to the main branch (tagged as "master")
  push:
    branches:
      - master
      
  workflow_dispatch:

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v3

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for qwerzl/betterdns
        uses: macbre/push-to-ghcr@v8
        with:
          image_name: qwerzl/betterdns
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}
